# https://taskfile.dev

version: '3'

silent: true

tasks:
  dev.dagster:
    desc: Start dagster for local development
    cmds:
      - dagster dev

  dev.db:
    desc: Connect to the development duckdb
    cmds:
      - duckdb dw/data/dev.duckdb

  dev.build:
    dir: dw
    cmds:
      - dbt build

  dev.run:
    dir: dw
    cmds:
      - dbt run

  dev.test:
    dir: dw
    cmds:
      - dbt test

