# https://taskfile.dev

version: '3'

silent: true

tasks:
  dev.dagster:
    desc: Start dagster for local development
    cmds:
      - dagster dev

  dev.db:
    desc: Connect to the development duckdb
    cmds:
      - duckdb data/dev.duckdb

  dev.build:
    desc: Build dbt project (run & test)
    dir: dw
    cmds:
      - dbt build

  dev.run:
    desc: Run dbt project
    dir: dw
    cmds:
      - dbt run

  dev.test:
    desc: Test dbt project
    dir: dw
    cmds:
      - dbt test

