dw:
  outputs:
    dev:
      type: duckdb
      schema: dw
      path: ../data/dev.duckdb
      threads: 1

    snd:
      type: starrocks
      schema: dw # database
      host: "{{ env_var('DW_HOST') }}" # snd.dw.db
      port: "{{ env_var('DW_PORT') }}" # 9030
      threads: 2
      username: "{{ env_var('DW_USER') }}"
      password: "{{ env_var('DW_PASSWORD') }}"

    prod:
      type: starrocks
      schema: dw # database
      host: "{{ env_var('DW_HOST') }}" # prd.dw.db
      port: "{{ env_var('DW_PORT') }}" # 9030
      username: "{{ env_var('DW_USER') }}"
      password: "{{ env_var('DW_PASSWORD') }}"
      threads: 4

  target: dev
