# https://taskfile.dev

version: '3'

silent: true

tasks:
  dagster:
    desc: Start dagster for local development
    cmds:
      - dagster dev

  db:
    desc: Connect to the development duckdb
    cmds:
      - duckdb data/dev.duckdb

  dbt.build:
    desc: Build dbt project (run & test)
    dir: dw
    cmds:
      - dbt build

  dbt.run:
    desc: Run dbt project
    dir: dw
    cmds:
      - dbt run

  dbt.test:
    desc: Test dbt project
    dir: dw
    cmds:
      - dbt test

  dbt.compile:
    desc: Compile dbt project
    dir: dw
    cmds:
      - dbt compile

  dbt.docs.gen:
    desc: Generate dbt project documentation
    dir: dw
    cmds:
      - dbt docs generate

  dbt.docs.serve:
    desc: Serve dbt project documentation
    dir: dw
    cmds:
      - dbt docs serve --port 3030
